CREATE TABLE `landing_recommendation_batches` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`published_at` integer
);
--> statement-breakpoint
CREATE INDEX `landing_recommendation_batches_published_idx` ON `landing_recommendation_batches` (`status`,`published_at`);
--> statement-breakpoint
CREATE TABLE `landing_recommendations` (
	`id` text PRIMARY KEY NOT NULL,
	`batch_id` text NOT NULL,
	`position` integer NOT NULL,
	`category` text NOT NULL,
	`question` text NOT NULL,
	`teaser` text NOT NULL,
	`image_url` text NOT NULL,
	`image_alt` text NOT NULL,
	`source_label` text NOT NULL,
	`source_url` text NOT NULL,
	`size` text DEFAULT 'standard' NOT NULL,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	FOREIGN KEY (`batch_id`) REFERENCES `landing_recommendation_batches`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `landing_recommendations_batch_position_unique` ON `landing_recommendations` (`batch_id`,`position`);
--> statement-breakpoint
CREATE INDEX `landing_recommendations_batch_idx` ON `landing_recommendations` (`batch_id`);
--> statement-breakpoint
INSERT INTO `landing_recommendation_batches` (`id`,`title`,`status`,`created_at`,`published_at`) VALUES ('initial-editorial-catalog','Initial editorial catalog','published',1784563200000,1784563200000);
--> statement-breakpoint
INSERT INTO `landing_recommendations` (`id`,`batch_id`,`position`,`category`,`question`,`teaser`,`image_url`,`image_alt`,`source_label`,`source_url`,`size`,`created_at`) VALUES
('grand-canyon','initial-editorial-catalog',0,'Nature','Why is the Grand Canyon so vast?','Uplift, rock, and a persistent river turned deep time into a visible landscape.','https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Grand_Canyon_view_from_Pima_Point_2010.jpg/1280px-Grand_Canyon_view_from_Pima_Point_2010.jpg','Layered red cliffs and mesas of the Grand Canyon seen from Pima Point','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Grand_Canyon_view_from_Pima_Point_2010.jpg','wide',1784563200000),
('pillars-of-creation','initial-editorial-catalog',1,'Space','How are stars born inside a cloud?','Cold columns of gas and dust hide young stars while radiation reshapes their nursery.','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Pillars_of_Creation_%28NIRCam_Image%29.jpg/1280px-Pillars_of_Creation_%28NIRCam_Image%29.jpg','James Webb Space Telescope view of the Pillars of Creation','NASA / ESA / CSA','https://commons.wikimedia.org/wiki/File:Pillars_of_Creation_(NIRCam_Image).jpg','tall',1784563200000),
('segovia-aqueduct','initial-editorial-catalog',2,'Technology','How did Rome move water without pumps?','A tiny, sustained slope let gravity carry water across cities and valleys.','https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Aqueduct_of_Segovia_08.jpg/1280px-Aqueduct_of_Segovia_08.jpg','The two-tiered stone arches of the Roman aqueduct in Segovia','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Aqueduct_of_Segovia_08.jpg','standard',1784563200000),
('cuneiform','initial-editorial-catalog',3,'History','What did the earliest writing keep track of?','Some of humanity''s oldest surviving marks recorded ordinary goods, labor, and accounts.','https://upload.wikimedia.org/wikipedia/commons/c/ca/Cuneiform_script2.jpg','Close view of wedge-shaped cuneiform marks pressed into a clay tablet','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Cuneiform_script2.jpg','compact',1784563200000),
('mercator-map','initial-editorial-catalog',4,'Systems','What can an accurate map still distort?','Mercator preserved compass bearings for sailors while stretching land near the poles.','https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Mercator_1569_world_map_composite.jpg/1280px-Mercator_1569_world_map_composite.jpg','Gerardus Mercator''s richly detailed 1569 world map','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Mercator_1569_world_map_composite.jpg','standard',1784563200000),
('apollo-footprint','initial-editorial-catalog',5,'Space','How long can a footprint last on the Moon?','With no wind or rain, a bootprint can outlast the people who made it by millions of years.','https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Apollo_11_bootprint.jpg/1280px-Apollo_11_bootprint.jpg','An Apollo 11 astronaut''s bootprint pressed into lunar dust','NASA','https://commons.wikimedia.org/wiki/File:Apollo_11_bootprint.jpg','compact',1784563200000),
('great-wave','initial-editorial-catalog',6,'Art','Why does this wave feel larger than the mountain?','Hokusai used scale, repetition, and a low horizon to turn a print into suspended motion.','https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/The_Great_Wave_off_Kanagawa.jpg/1280px-The_Great_Wave_off_Kanagawa.jpg','Hokusai''s Great Wave rising above boats with Mount Fuji in the distance','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:The_Great_Wave_off_Kanagawa.jpg','wide',1784563200000),
('blue-marble','initial-editorial-catalog',7,'Space','Why did one photograph change how Earth looked?','Apollo 17 framed a whole, finite planet with weather and continents sharing one sphere.','https://upload.wikimedia.org/wikipedia/commons/thumb/9/97/The_Earth_seen_from_Apollo_17.jpg/1280px-The_Earth_seen_from_Apollo_17.jpg','The blue-and-white Earth photographed by the Apollo 17 crew','NASA','https://commons.wikimedia.org/wiki/File:The_Earth_seen_from_Apollo_17.jpg','tall',1784563200000),
('rosetta-stone','initial-editorial-catalog',8,'History','How did one stone unlock a lost script?','The same decree written three ways gave scholars a bridge into Egyptian hieroglyphs.','https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Rosetta_Stone.JPG/1280px-Rosetta_Stone.JPG','The dark granodiorite Rosetta Stone covered with three bands of script','British Museum','https://commons.wikimedia.org/wiki/File:Rosetta_Stone.JPG','standard',1784563200000),
('starry-night','initial-editorial-catalog',9,'Art','Can painted turbulence behave like real turbulence?','The sky''s whorls invite a surprising comparison between visual rhythm and fluid motion.','https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1280px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg','Vincent van Gogh''s The Starry Night with a swirling blue night sky','MoMA / Google Arts','https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg','standard',1784563200000),
('archaeopteryx','initial-editorial-catalog',10,'Nature','What makes a fossil look both bird and dinosaur?','Feathers, teeth, claws, and a long bony tail preserve evolution''s mosaic pattern.','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Gfp-archaeopteryx.jpg/1280px-Gfp-archaeopteryx.jpg','A detailed Archaeopteryx fossil slab showing its feather impressions and skeleton','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Gfp-archaeopteryx.jpg','compact',1784563200000),
('honeybee','initial-editorial-catalog',11,'Nature','How does a bee tell flowers apart?','Color, scent, pattern, and ultraviolet markings turn a flower into a navigable signal.','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/European_honey_bee_extracts_nectar.jpg/960px-European_honey_bee_extracts_nectar.jpg','A European honey bee extracting nectar from a flower','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:European_honey_bee_extracts_nectar.jpg','standard',1784563200000),
('taal-volcano','initial-editorial-catalog',12,'Nature','Why can a volcano make its own lightning?','Colliding ash and ice particles can separate electrical charge inside an eruption plume.','https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Taal_Volcano_eruption_on_January_12%2C_2020.jpg/960px-Taal_Volcano_eruption_on_January_12%2C_2020.jpg','A towering ash plume during the 2020 eruption of Taal Volcano','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Taal_Volcano_eruption_on_January_12,_2020.jpg','standard',1784563200000),
('blue-whale','initial-editorial-catalog',13,'Nature','How can a blue whale grow so enormous?','Dense prey, efficient feeding, and buoyant water let one body exceed every land animal.','https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Blow_of_a_blue_whale_in_the_Arctic_sea.jpg/960px-Blow_of_a_blue_whale_in_the_Arctic_sea.jpg','The blow and back of a blue whale breaking the Arctic sea surface','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Blow_of_a_blue_whale_in_the_Arctic_sea.jpg','standard',1784563200000),
('dna','initial-editorial-catalog',14,'Science','Why does DNA twist into a double helix?','Molecular bonds, water, and paired bases stabilize a compact structure that can be copied.','https://upload.wikimedia.org/wikipedia/commons/c/c4/DNA_double_helix_horizontal.png','Molecular model of a horizontal DNA double helix','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:DNA_double_helix_horizontal.png','standard',1784563200000),
('saturn-rings','initial-editorial-catalog',15,'Space','Why are Saturn''s rings so flat?','Collisions cancel vertical motion while countless icy particles continue orbiting together.','https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Top_view_of_the_rings_of_Saturn_by_Cassini_-_October_10%2C_2013.jpg/960px-Top_view_of_the_rings_of_Saturn_by_Cassini_-_October_10%2C_2013.jpg','Cassini spacecraft view across Saturn''s rings','NASA / Cassini','https://commons.wikimedia.org/wiki/File:Top_view_of_the_rings_of_Saturn_by_Cassini_-_October_10,_2013.jpg','standard',1784563200000),
('coral-reef','initial-editorial-catalog',16,'Nature','How does a reef become a living city?','Corals build structure while fish, microbes, algae, and currents exchange shelter and energy.','https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Soft_coral_peach_komodo.jpg/960px-Soft_coral_peach_komodo.jpg','Peach-colored soft coral and reef life in Komodo waters','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Soft_coral_peach_komodo.jpg','standard',1784563200000),
('golden-gate','initial-editorial-catalog',17,'Technology','How does a suspension bridge hold itself up?','Main cables turn the deck''s load into tension and deliver it to towers and anchorages.','https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/San_Francisco_%28CA%2C_USA%29%2C_Golden_Gate_Bridge_--_2022_--_3023_%28bw%29.jpg/960px-San_Francisco_%28CA%2C_USA%29%2C_Golden_Gate_Bridge_--_2022_--_3023_%28bw%29.jpg','Black-and-white view along the Golden Gate Bridge','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:San_Francisco_(CA,_USA),_Golden_Gate_Bridge_--_2022_--_3023_(bw).jpg','standard',1784563200000),
('bauhaus','initial-editorial-catalog',18,'Art','Why did the Bauhaus make buildings look modern?','Visible structure, industrial materials, and functional space replaced historical ornament.','https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Dessau_Bauhaus-Geb%C3%A4ude_asv2024-06_img1.jpg/960px-Dessau_Bauhaus-Geb%C3%A4ude_asv2024-06_img1.jpg','Glass curtain wall and white volumes of the Bauhaus building in Dessau','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Dessau_Bauhaus-Geb%C3%A4ude_asv2024-06_img1.jpg','standard',1784563200000),
('printing-press','initial-editorial-catalog',19,'Technology','How did printing make ideas travel faster?','Reusable type and repeatable pressure turned individual pages into scalable networks of copies.','https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Old_Threshers_Miehle_Press_Drum.jpg/960px-Old_Threshers_Miehle_Press_Drum.jpg','Large metal drum and mechanisms of a historic printing press','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Old_Threshers_Miehle_Press_Drum.jpg','standard',1784563200000),
('silk-road-map','initial-editorial-catalog',20,'History','Was the Silk Road really one road?','Overlapping land and sea routes moved goods, beliefs, technologies, and diseases across continents.','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/%E4%B8%9D%E8%B7%AF%E5%B1%B1%E6%B0%B4%E5%9C%B0%E5%9B%BE.tif/lossy-page1-960px-%E4%B8%9D%E8%B7%AF%E5%B1%B1%E6%B0%B4%E5%9C%B0%E5%9B%BE.tif.jpg','Long illustrated Chinese map associated with Silk Road landscapes','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:%E4%B8%9D%E8%B7%AF%E5%B1%B1%E6%B0%B4%E5%9C%B0%E5%9B%BE.tif','standard',1784563200000),
('eiffel-tower','initial-editorial-catalog',21,'Systems','Why can an iron tower survive strong wind?','A porous lattice guides wind through the structure while curved legs spread force downward.','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Tour_Eiffel_Wikimedia_Commons.jpg/960px-Tour_Eiffel_Wikimedia_Commons.jpg','The iron lattice structure of the Eiffel Tower seen from below','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Tour_Eiffel_Wikimedia_Commons.jpg','standard',1784563200000),
('taj-mahal','initial-editorial-catalog',22,'Culture','How does the Taj Mahal appear perfectly balanced?','Symmetry, repeated arches, reflected light, and carefully scaled minarets organize the whole view.','https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Taj_Mahal%2C_Agra%2C_India_edit3.jpg/960px-Taj_Mahal%2C_Agra%2C_India_edit3.jpg','The white marble Taj Mahal and its reflecting pool in Agra','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Taj_Mahal,_Agra,_India_edit3.jpg','standard',1784563200000),
('alpine-lake','initial-editorial-catalog',23,'Nature','How does a glacier carve a mountain valley?','Moving ice plucks rock, grinds slopes, and leaves broad U-shaped valleys behind.','https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Fronalpstock_big.jpg/960px-Fronalpstock_big.jpg','Alpine mountains and a long blue lake seen from Fronalpstock','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Fronalpstock_big.jpg','standard',1784563200000),
('mona-lisa','initial-editorial-catalog',24,'Art','Why does the Mona Lisa''s expression seem to change?','Soft transitions and peripheral vision make the mouth read differently as the eye moves.','https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Mona_Lisa.jpg/960px-Mona_Lisa.jpg','Leonardo da Vinci''s portrait known as the Mona Lisa','Musée du Louvre','https://commons.wikimedia.org/wiki/File:Mona_Lisa.jpg','standard',1784563200000),
('machu-picchu','initial-editorial-catalog',25,'History','How did people build a city between mountain peaks?','Terraces, fitted stone, drainage, and steep paths adapted urban life to an extreme landscape.','https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Machu_Picchu%2C_Per%C3%BA%2C_2015-07-30%2C_DD_47.JPG/960px-Machu_Picchu%2C_Per%C3%BA%2C_2015-07-30%2C_DD_47.JPG','Stone buildings and green terraces of Machu Picchu between mountain peaks','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Machu_Picchu,_Per%C3%BA,_2015-07-30,_DD_47.JPG','standard',1784563200000),
('antikythera','initial-editorial-catalog',26,'Technology','How could an ancient machine predict the sky?','Interlocking bronze gears modeled astronomical cycles long before modern clockwork.','https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Antikythera_Mechanism_-_National_Archaeological_Museum%2C_Athens_by_Joy_of_Museum.jpg/960px-Antikythera_Mechanism_-_National_Archaeological_Museum%2C_Athens_by_Joy_of_Museum.jpg','Corroded bronze fragments of the Antikythera mechanism in a museum display','National Archaeological Museum','https://commons.wikimedia.org/wiki/File:Antikythera_Mechanism_-_National_Archaeological_Museum,_Athens_by_Joy_of_Museum.jpg','standard',1784563200000),
('octopus','initial-editorial-catalog',27,'Nature','How does an octopus change its appearance so quickly?','Pigment cells, reflective tissues, and muscular skin change color, brightness, and texture together.','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Pulpo_com%C3%BAn_%28Octopus_vulgaris%29%2C_Parque_natural_de_la_Arr%C3%A1bida%2C_Portugal%2C_2020-07-21%2C_DD_33.jpg/960px-Pulpo_com%C3%BAn_%28Octopus_vulgaris%29%2C_Parque_natural_de_la_Arr%C3%A1bida%2C_Portugal%2C_2020-07-21%2C_DD_33.jpg','A common octopus camouflaged against rocks underwater in Portugal','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Pulpo_com%C3%BAn_(Octopus_vulgaris),_Parque_natural_de_la_Arr%C3%A1bida,_Portugal,_2020-07-21,_DD_33.jpg','standard',1784563200000),
('wind-farm','initial-editorial-catalog',28,'Technology','How does a wind farm turn moving air into power?','Blades capture kinetic energy while controls coordinate generators across changing wind.','https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Power_County_Wind_Farm_002.jpg/960px-Power_County_Wind_Farm_002.jpg','Rows of wind turbines across an open landscape at Power County Wind Farm','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Power_County_Wind_Farm_002.jpg','standard',1784563200000),
('pantheon-dome','initial-editorial-catalog',29,'Systems','Why has the Pantheon''s concrete dome survived?','The dome becomes thinner and lighter toward an open oculus while hidden geometry carries compression.','https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Dome_of_Pantheon_%28Rome%29.jpg/960px-Dome_of_Pantheon_%28Rome%29.jpg','Coffered interior of the Pantheon dome rising toward its circular oculus','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Dome_of_Pantheon_(Rome).jpg','standard',1784563200000),
('ada-lovelace','initial-editorial-catalog',30,'History','What did Ada Lovelace imagine computers could become?','She saw that a calculating machine might manipulate symbols, not merely produce numbers.','https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ada_Lovelace_portrait.jpg/960px-Ada_Lovelace_portrait.jpg','Painted portrait of mathematician and computing pioneer Ada Lovelace','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Ada_Lovelace_portrait.jpg','standard',1784563200000),
('lascaux','initial-editorial-catalog',31,'Culture','Why did people paint animals deep inside caves?','Placement, movement, ritual, memory, and storytelling remain possible clues rather than one settled answer.','https://upload.wikimedia.org/wikipedia/commons/1/1e/Lascaux_painting.jpg','Prehistoric animal paintings across the pale stone wall of Lascaux cave','Wikimedia Commons','https://commons.wikimedia.org/wiki/File:Lascaux_painting.jpg','standard',1784563200000);
