CREATE TABLE `landing_recommendation_dimensions` (
	`recommendation_id` text NOT NULL,
	`dimension` text NOT NULL,
	`position` integer NOT NULL,
	PRIMARY KEY(`recommendation_id`, `dimension`),
	FOREIGN KEY (`recommendation_id`) REFERENCES `landing_recommendations`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX `landing_recommendation_dimensions_position_unique` ON `landing_recommendation_dimensions` (`recommendation_id`,`position`);
--> statement-breakpoint
CREATE INDEX `landing_recommendation_dimensions_filter_idx` ON `landing_recommendation_dimensions` (`dimension`,`recommendation_id`);
--> statement-breakpoint
INSERT INTO `landing_recommendation_dimensions` (`recommendation_id`,`dimension`,`position`)
SELECT
	`id`,
	CASE `category`
		WHEN 'Nature' THEN 'Living World'
		WHEN 'Science' THEN 'Forces & Energy'
		WHEN 'History' THEN 'Time & History'
		WHEN 'Culture' THEN 'Society'
		WHEN 'Systems' THEN 'Design & Technology'
		WHEN 'Space' THEN 'Cosmos'
		WHEN 'Technology' THEN 'Design & Technology'
		WHEN 'Art' THEN 'Art & Expression'
		ELSE 'Society'
	END,
	0
FROM `landing_recommendations`;
--> statement-breakpoint
--> statement-breakpoint
--> statement-breakpoint
-- curated landing dimensions
DELETE FROM `landing_recommendation_dimensions`
WHERE `recommendation_id` IN ('mars-blue-sunset','hydrothermal-vent-life','axolotl-regeneration','singing-sand','snowflake-sixfold','glass-frog-transparency','monarch-super-generation','mangrove-salt','inca-quipu','nazca-lines','roman-dodecahedron','sutton-hoo-imprint','submarine-cables','maeslant-barrier','termite-mound-airflow','phantom-traffic-jam','shape-memory-metal','webb-origami','pointillist-color','m87-black-hole','giants-causeway-cooling','racetrack-sailing-stones','living-blue-waves','socotra-dragon-blood-trees','synchronous-fireflies','starling-murmuration','archerfish-refraction','mantis-shrimp-polarized-vision','vampire-squid-glowing-defense','comb-jelly-rainbow','webb-pillars-creation','cosmic-horseshoe-lensing','pulsar-cosmic-lighthouse','ferrofluid-spikes','chladni-sound-patterns','blue-morpho-structural-color','gobekli-tepe-monuments','lycurgus-cup-color-change','egyptian-blue-pigment','antarctica-blood-falls','blue-dragon-upside-down','venus-flytrap-counting','tsingy-stone-forest','sea-ice-frost-flowers','grand-prismatic-living-thermometer','leidenfrost-vapor-skating','lalibela-carved-downward','falkirk-rotating-boat-lift','petra-rain-engineering','uros-floating-reed-islands','qeswachaka-annual-bridge','kente-strips-to-prestige','living-root-bridge','ifugao-water-staircase','atacama-fog-harvesting','aerogel-catches-comets','gecko-dry-adhesive','fiber-optic-corner-light','atkins-sun-printed-algae','holbein-hidden-skull','kintsugi-visible-repair','saturn-polar-hexagon','europa-chaos-ice-rafts','solar-magnetic-prominence','orchid-mantis-flower-disguise','kelvin-helmholtz-cloud-waves','pazyryk-carpet-frozen-color','inuit-snow-goggles-slit-vision','xochimilco-chinampa-living-grid','hh211-newborn-star-jet','lightsail-photon-pressure','pietra-dura-stone-painting','leaf-tailed-gecko-dead-leaf','fata-morgana-stacked-horizon','archimedes-palimpsest-hidden-math','castells-human-tower-foundation','venice-submerged-timber-foundations','io-tvashtar-volcanic-fountain','octobot-soft-chemical-logic','cloisonne-wire-cells','crown-shyness-rivers-of-sky','lotus-effect-rolling-water','phaistos-disc-stamped-script','temari-thread-geometry','beaver-dam-wetland-engineer','butterfly-nebula-hidden-star','lung-on-chip-breathing-membrane','quilling-paper-volume','thorny-devil-skin-straws','lencois-rain-lagoons','thermokarst-methane-bubbles','aurora-gas-color-code','soap-bubble-pop-clock','radiolarian-glass-cathedral','derinkuyu-underground-breathing','pompeii-ash-void-casts','dunhuang-sealed-library-cave','tollund-bog-tanned-face','moon-jar-joined-hemispheres','marshallese-wave-stick-chart','ghanaian-life-story-coffins','indigo-air-reveals-blue','pysanky-wax-written-color','oaxacan-alebrije-hybrid-creatures','leafcutter-ant-fungus-farm','bali-subak-water-temples','dutch-sand-motor-coast','pluto-heart-lava-lamp','mars-carbon-dioxide-spiders','cartwheel-galaxy-collision-ripple','cats-eye-eleven-shells','vine-robot-tip-growth','loftid-inflatable-heat-shield','flat-metalens-nanopillars','mexican-feather-mosaic-light','lusterware-metallic-clay','ebru-painting-on-water','fore-edge-disappearing-painting','rainbow-eucalyptus-bark-clock','nacreous-clouds-after-sunset','nebra-sky-disc-portable-cosmos','dorodango-mud-mirror','qanat-desert-dotted-line','reiner-gamma-magnetic-sunscreen','odeillo-sunlight-furnace','isfahan-muqarnas-light-honeycomb','leafy-seadragon-false-leaves','bubble-chamber-invisible-tracks','han-jade-burial-suit','sand-mandala-impermanence','ladakh-ice-stupa-spring-water','enceladus-ocean-geysers','apollo-core-rope-software','terracotta-soft-veil','corpse-flower-heat-and-scent','hair-ice-fungal-sculptor','oseberg-clinker-hull','wayang-sculpture-and-shadow','chand-baori-changing-waterline','v838-mon-light-echo','acoustic-levitation-standing-wave','nested-puzzle-ball','blue-footed-booby-courtship-steps','penitentes-sun-carved-ice','shigir-idol-peat-time-capsule','guna-mola-reverse-applique','yakhchal-desert-ice-house','mira-thirteen-light-year-tail','transparent-wood-light-window','micromosaic-glass-painting','giant-clam-solar-farm','ijen-burning-blue-sulfur','herculaneum-scroll-virtual-unwrapping','imigongo-earth-relief-patterns','whale-fall-deep-sea-succession','hoags-object-ring-within-ring','nanobionic-glowing-plants','carved-lacquer-hidden-layers','satin-bowerbird-blue-gallery','lichtenberg-frozen-lightning','great-zimbabwe-dry-stone-curves','maori-feather-cloak-weaving','salmon-carry-ocean-into-forest','phobos-stickney-near-shatter','frequency-comb-ruler-for-light','bojagi-scraps-into-light','frogfish-fin-fishing-rod','green-flash-last-sunlight','cyrus-cylinder-buried-proclamation','roman-hypocaust-heated-floor','solar-corona-hotter-than-surface','bacterial-concrete-heals-cracks','pygmy-seahorse-coral-camouflage','light-pillars-floating-mirrors','sanxingdui-protruding-eyes','kintsugi-golden-repair','living-root-bridge-stronger','daphnis-ring-wavemaker','aerogel-solid-smoke','holbein-anamorphic-skull','peacock-spider-rainbow-fan','snow-rollers-wind-sculpture','lion-man-mammoth-ivory','zellige-infinite-geometry','fog-net-drinking-water','ceres-occator-salt-deposits','gecko-gripper-space','goryeo-celadon-hidden-inlay','resurrection-plant-rehydration','romanesco-fibonacci-growth','terracotta-warriors-lost-color','shipibo-kene-visual-language','qeswachaka-annual-rebuild','eta-carinae-survived-eruption','robobee-paperclip-flight','arcimboldo-vertumnus-harvest-face','giant-waterlily-floating-truss','fallstreak-hole-aircraft','dogu-goggle-eyes','gelede-masks-oral-history','aflaj-water-by-time','pan-flying-saucer-moon','pufferfish-underwater-sand-garden','pollia-berry-color-without-pigment','pistol-shrimp-flashing-cavitation','siphonophore-colony-one-body','wood-frog-freezes-and-restarts','red-sprites-above-thunderstorms','naica-giant-gypsum-crystals','brocken-spectre-rainbow-shadow','rainbow-is-really-a-circle','egyptian-blue-hippo-lotus-rebirth','liangzhu-jade-cong-enigma','oxus-gold-chariot-protective-face','babylon-processional-brick-lions','djenne-mosque-annual-replastering','jeju-haenyeo-one-breath-harvest','theyyam-costume-living-deity','ikat-pattern-dyed-before-weaving','dutch-sand-motor-moving-coast','oyster-reef-filter-and-breakwater','slime-mold-designs-rail-network','red-rectangle-nebula-ladder','miranda-patchwork-moon-cliffs','cosmic-hand-pulsar-wind-nebula','comet-67p-rubber-duck-collision','origami-solar-array-bloom','metal-foam-floats-on-water','sofi-soft-robotic-fish','millefiori-thousand-glass-flowers','martinez-black-on-black-pottery','reverse-glass-painting-backward');
--> statement-breakpoint
WITH `curated` (`recommendation_id`,`dimension`,`position`) AS (VALUES
	('mars-blue-sunset','Cosmos',0),
	('hydrothermal-vent-life','Living World',0),
	('hydrothermal-vent-life','Cosmos',1),
	('axolotl-regeneration','Living World',0),
	('axolotl-regeneration','Body',1),
	('singing-sand','Forces & Energy',0),
	('singing-sand','Planet Earth',1),
	('singing-sand','Matter',2),
	('snowflake-sixfold','Matter',0),
	('snowflake-sixfold','Planet Earth',1),
	('glass-frog-transparency','Living World',0),
	('glass-frog-transparency','Body',1),
	('glass-frog-transparency','Matter',2),
	('monarch-super-generation','Living World',0),
	('mangrove-salt','Living World',0),
	('mangrove-salt','Body',1),
	('mangrove-salt','Planet Earth',2),
	('inca-quipu','Society',0),
	('inca-quipu','Language',1),
	('inca-quipu','Time & History',2),
	('nazca-lines','Time & History',0),
	('roman-dodecahedron','Time & History',0),
	('sutton-hoo-imprint','Time & History',0),
	('submarine-cables','Design & Technology',0),
	('submarine-cables','Planet Earth',1),
	('maeslant-barrier','Design & Technology',0),
	('maeslant-barrier','Planet Earth',1),
	('termite-mound-airflow','Living World',0),
	('phantom-traffic-jam','Society',0),
	('shape-memory-metal','Design & Technology',0),
	('shape-memory-metal','Matter',1),
	('webb-origami','Design & Technology',0),
	('webb-origami','Planet Earth',1),
	('webb-origami','Cosmos',2),
	('pointillist-color','Art & Expression',0),
	('pointillist-color','Mind',1),
	('pointillist-color','Forces & Energy',2),
	('m87-black-hole','Cosmos',0),
	('m87-black-hole','Planet Earth',1),
	('m87-black-hole','Design & Technology',2),
	('giants-causeway-cooling','Living World',0),
	('giants-causeway-cooling','Planet Earth',1),
	('giants-causeway-cooling','Matter',2),
	('giants-causeway-cooling','Numbers & Logic',3),
	('racetrack-sailing-stones','Forces & Energy',0),
	('racetrack-sailing-stones','Planet Earth',1),
	('racetrack-sailing-stones','Matter',2),
	('living-blue-waves','Living World',0),
	('living-blue-waves','Planet Earth',1),
	('living-blue-waves','Forces & Energy',2),
	('socotra-dragon-blood-trees','Living World',0),
	('synchronous-fireflies','Living World',0),
	('synchronous-fireflies','Mind',1),
	('synchronous-fireflies','Forces & Energy',2),
	('starling-murmuration','Living World',0),
	('starling-murmuration','Mind',1),
	('archerfish-refraction','Living World',0),
	('archerfish-refraction','Mind',1),
	('archerfish-refraction','Planet Earth',2),
	('archerfish-refraction','Matter',3),
	('mantis-shrimp-polarized-vision','Mind',0),
	('mantis-shrimp-polarized-vision','Living World',1),
	('mantis-shrimp-polarized-vision','Forces & Energy',2),
	('vampire-squid-glowing-defense','Living World',0),
	('vampire-squid-glowing-defense','Mind',1),
	('comb-jelly-rainbow','Forces & Energy',0),
	('comb-jelly-rainbow','Planet Earth',1),
	('webb-pillars-creation','Cosmos',0),
	('webb-pillars-creation','Design & Technology',1),
	('cosmic-horseshoe-lensing','Cosmos',0),
	('cosmic-horseshoe-lensing','Numbers & Logic',1),
	('cosmic-horseshoe-lensing','Design & Technology',2),
	('pulsar-cosmic-lighthouse','Cosmos',0),
	('pulsar-cosmic-lighthouse','Forces & Energy',1),
	('ferrofluid-spikes','Design & Technology',0),
	('ferrofluid-spikes','Forces & Energy',1),
	('chladni-sound-patterns','Art & Expression',0),
	('chladni-sound-patterns','Matter',1),
	('chladni-sound-patterns','Forces & Energy',2),
	('chladni-sound-patterns','Numbers & Logic',3),
	('blue-morpho-structural-color','Matter',0),
	('blue-morpho-structural-color','Living World',1),
	('blue-morpho-structural-color','Forces & Energy',2),
	('gobekli-tepe-monuments','Time & History',0),
	('gobekli-tepe-monuments','Belief & Ideas',1),
	('gobekli-tepe-monuments','Matter',2),
	('lycurgus-cup-color-change','Society',0),
	('lycurgus-cup-color-change','Matter',1),
	('lycurgus-cup-color-change','Forces & Energy',2),
	('lycurgus-cup-color-change','Time & History',3),
	('egyptian-blue-pigment','Art & Expression',0),
	('egyptian-blue-pigment','Matter',1),
	('egyptian-blue-pigment','Time & History',2),
	('antarctica-blood-falls','Matter',0),
	('antarctica-blood-falls','Living World',1),
	('antarctica-blood-falls','Planet Earth',2),
	('blue-dragon-upside-down','Living World',0),
	('blue-dragon-upside-down','Body',1),
	('blue-dragon-upside-down','Planet Earth',2),
	('venus-flytrap-counting','Living World',0),
	('tsingy-stone-forest','Living World',0),
	('tsingy-stone-forest','Planet Earth',1),
	('tsingy-stone-forest','Matter',2),
	('tsingy-stone-forest','Art & Expression',3),
	('sea-ice-frost-flowers','Matter',0),
	('sea-ice-frost-flowers','Planet Earth',1),
	('grand-prismatic-living-thermometer','Living World',0),
	('grand-prismatic-living-thermometer','Planet Earth',1),
	('leidenfrost-vapor-skating','Forces & Energy',0),
	('leidenfrost-vapor-skating','Matter',1),
	('lalibela-carved-downward','Time & History',0),
	('lalibela-carved-downward','Belief & Ideas',1),
	('lalibela-carved-downward','Planet Earth',2),
	('lalibela-carved-downward','Art & Expression',3),
	('falkirk-rotating-boat-lift','Design & Technology',0),
	('falkirk-rotating-boat-lift','Forces & Energy',1),
	('petra-rain-engineering','Time & History',0),
	('petra-rain-engineering','Planet Earth',1),
	('petra-rain-engineering','Matter',2),
	('petra-rain-engineering','Forces & Energy',3),
	('uros-floating-reed-islands','Society',0),
	('uros-floating-reed-islands','Planet Earth',1),
	('uros-floating-reed-islands','Design & Technology',2),
	('qeswachaka-annual-bridge','Society',0),
	('qeswachaka-annual-bridge','Time & History',1),
	('qeswachaka-annual-bridge','Design & Technology',2),
	('kente-strips-to-prestige','Society',0),
	('kente-strips-to-prestige','Art & Expression',1),
	('living-root-bridge','Design & Technology',0),
	('living-root-bridge','Living World',1),
	('ifugao-water-staircase','Time & History',0),
	('ifugao-water-staircase','Food & Agriculture',1),
	('ifugao-water-staircase','Planet Earth',2),
	('ifugao-water-staircase','Matter',3),
	('atacama-fog-harvesting','Design & Technology',0),
	('atacama-fog-harvesting','Planet Earth',1),
	('atacama-fog-harvesting','Matter',2),
	('aerogel-catches-comets','Design & Technology',0),
	('aerogel-catches-comets','Cosmos',1),
	('aerogel-catches-comets','Matter',2),
	('gecko-dry-adhesive','Design & Technology',0),
	('gecko-dry-adhesive','Body',1),
	('gecko-dry-adhesive','Living World',2),
	('fiber-optic-corner-light','Design & Technology',0),
	('fiber-optic-corner-light','Matter',1),
	('fiber-optic-corner-light','Forces & Energy',2),
	('fiber-optic-corner-light','Art & Expression',3),
	('atkins-sun-printed-algae','Art & Expression',0),
	('atkins-sun-printed-algae','Planet Earth',1),
	('atkins-sun-printed-algae','Cosmos',2),
	('holbein-hidden-skull','Art & Expression',0),
	('holbein-hidden-skull','Mind',1),
	('kintsugi-visible-repair','Art & Expression',0),
	('kintsugi-visible-repair','Matter',1),
	('saturn-polar-hexagon','Cosmos',0),
	('saturn-polar-hexagon','Planet Earth',1),
	('saturn-polar-hexagon','Numbers & Logic',2),
	('europa-chaos-ice-rafts','Cosmos',0),
	('europa-chaos-ice-rafts','Planet Earth',1),
	('europa-chaos-ice-rafts','Matter',2),
	('solar-magnetic-prominence','Cosmos',0),
	('solar-magnetic-prominence','Forces & Energy',1),
	('orchid-mantis-flower-disguise','Living World',0),
	('orchid-mantis-flower-disguise','Mind',1),
	('kelvin-helmholtz-cloud-waves','Forces & Energy',0),
	('kelvin-helmholtz-cloud-waves','Planet Earth',1),
	('pazyryk-carpet-frozen-color','Time & History',0),
	('pazyryk-carpet-frozen-color','Planet Earth',1),
	('pazyryk-carpet-frozen-color','Matter',2),
	('pazyryk-carpet-frozen-color','Forces & Energy',3),
	('inuit-snow-goggles-slit-vision','Society',0),
	('inuit-snow-goggles-slit-vision','Planet Earth',1),
	('xochimilco-chinampa-living-grid','Food & Agriculture',0),
	('xochimilco-chinampa-living-grid','Living World',1),
	('xochimilco-chinampa-living-grid','Planet Earth',2),
	('xochimilco-chinampa-living-grid','Numbers & Logic',3),
	('hh211-newborn-star-jet','Cosmos',0),
	('lightsail-photon-pressure','Design & Technology',0),
	('lightsail-photon-pressure','Cosmos',1),
	('lightsail-photon-pressure','Forces & Energy',2),
	('lightsail-photon-pressure','Art & Expression',3),
	('pietra-dura-stone-painting','Art & Expression',0),
	('pietra-dura-stone-painting','Matter',1),
	('leaf-tailed-gecko-dead-leaf','Living World',0),
	('leaf-tailed-gecko-dead-leaf','Mind',1),
	('fata-morgana-stacked-horizon','Forces & Energy',0),
	('archimedes-palimpsest-hidden-math','Time & History',0),
	('archimedes-palimpsest-hidden-math','Language',1),
	('castells-human-tower-foundation','Society',0),
	('castells-human-tower-foundation','Design & Technology',1),
	('venice-submerged-timber-foundations','Design & Technology',0),
	('venice-submerged-timber-foundations','Matter',1),
	('venice-submerged-timber-foundations','Time & History',2),
	('io-tvashtar-volcanic-fountain','Cosmos',0),
	('io-tvashtar-volcanic-fountain','Planet Earth',1),
	('octobot-soft-chemical-logic','Design & Technology',0),
	('octobot-soft-chemical-logic','Matter',1),
	('octobot-soft-chemical-logic','Numbers & Logic',2),
	('cloisonne-wire-cells','Art & Expression',0),
	('cloisonne-wire-cells','Matter',1),
	('cloisonne-wire-cells','Design & Technology',2),
	('crown-shyness-rivers-of-sky','Living World',0),
	('crown-shyness-rivers-of-sky','Planet Earth',1),
	('lotus-effect-rolling-water','Matter',0),
	('lotus-effect-rolling-water','Living World',1),
	('lotus-effect-rolling-water','Planet Earth',2),
	('phaistos-disc-stamped-script','Time & History',0),
	('phaistos-disc-stamped-script','Language',1),
	('temari-thread-geometry','Society',0),
	('temari-thread-geometry','Matter',1),
	('temari-thread-geometry','Numbers & Logic',2),
	('temari-thread-geometry','Art & Expression',3),
	('beaver-dam-wetland-engineer','Living World',0),
	('beaver-dam-wetland-engineer','Planet Earth',1),
	('butterfly-nebula-hidden-star','Cosmos',0),
	('butterfly-nebula-hidden-star','Living World',1),
	('butterfly-nebula-hidden-star','Forces & Energy',2),
	('butterfly-nebula-hidden-star','Art & Expression',3),
	('lung-on-chip-breathing-membrane','Design & Technology',0),
	('lung-on-chip-breathing-membrane','Body',1),
	('quilling-paper-volume','Art & Expression',0),
	('thorny-devil-skin-straws','Living World',0),
	('thorny-devil-skin-straws','Body',1),
	('lencois-rain-lagoons','Living World',0),
	('lencois-rain-lagoons','Planet Earth',1),
	('thermokarst-methane-bubbles','Matter',0),
	('thermokarst-methane-bubbles','Planet Earth',1),
	('thermokarst-methane-bubbles','Forces & Energy',2),
	('aurora-gas-color-code','Forces & Energy',0),
	('aurora-gas-color-code','Cosmos',1),
	('aurora-gas-color-code','Matter',2),
	('soap-bubble-pop-clock','Matter',0),
	('soap-bubble-pop-clock','Forces & Energy',1),
	('radiolarian-glass-cathedral','Living World',0),
	('radiolarian-glass-cathedral','Body',1),
	('radiolarian-glass-cathedral','Matter',2),
	('derinkuyu-underground-breathing','Time & History',0),
	('derinkuyu-underground-breathing','Society',1),
	('derinkuyu-underground-breathing','Design & Technology',2),
	('pompeii-ash-void-casts','Time & History',0),
	('pompeii-ash-void-casts','Body',1),
	('dunhuang-sealed-library-cave','Time & History',0),
	('dunhuang-sealed-library-cave','Language',1),
	('dunhuang-sealed-library-cave','Planet Earth',2),
	('tollund-bog-tanned-face','Time & History',0),
	('moon-jar-joined-hemispheres','Society',0),
	('moon-jar-joined-hemispheres','Cosmos',1),
	('marshallese-wave-stick-chart','Society',0),
	('marshallese-wave-stick-chart','Planet Earth',1),
	('marshallese-wave-stick-chart','Cosmos',2),
	('marshallese-wave-stick-chart','Forces & Energy',3),
	('ghanaian-life-story-coffins','Society',0),
	('ghanaian-life-story-coffins','Living World',1),
	('indigo-air-reveals-blue','Society',0),
	('indigo-air-reveals-blue','Matter',1),
	('indigo-air-reveals-blue','Art & Expression',2),
	('pysanky-wax-written-color','Society',0),
	('pysanky-wax-written-color','Forces & Energy',1),
	('pysanky-wax-written-color','Art & Expression',2),
	('oaxacan-alebrije-hybrid-creatures','Society',0),
	('oaxacan-alebrije-hybrid-creatures','Living World',1),
	('leafcutter-ant-fungus-farm','Living World',0),
	('leafcutter-ant-fungus-farm','Food & Agriculture',1),
	('bali-subak-water-temples','Society',0),
	('bali-subak-water-temples','Belief & Ideas',1),
	('bali-subak-water-temples','Food & Agriculture',2),
	('bali-subak-water-temples','Planet Earth',3),
	('dutch-sand-motor-coast','Design & Technology',0),
	('dutch-sand-motor-coast','Planet Earth',1),
	('dutch-sand-motor-coast','Forces & Energy',2),
	('pluto-heart-lava-lamp','Cosmos',0),
	('pluto-heart-lava-lamp','Planet Earth',1),
	('mars-carbon-dioxide-spiders','Cosmos',0),
	('mars-carbon-dioxide-spiders','Living World',1),
	('mars-carbon-dioxide-spiders','Art & Expression',2),
	('cartwheel-galaxy-collision-ripple','Cosmos',0),
	('cartwheel-galaxy-collision-ripple','Forces & Energy',1),
	('cats-eye-eleven-shells','Cosmos',0),
	('vine-robot-tip-growth','Design & Technology',0),
	('loftid-inflatable-heat-shield','Design & Technology',0),
	('loftid-inflatable-heat-shield','Forces & Energy',1),
	('flat-metalens-nanopillars','Design & Technology',0),
	('flat-metalens-nanopillars','Matter',1),
	('flat-metalens-nanopillars','Forces & Energy',2),
	('mexican-feather-mosaic-light','Art & Expression',0),
	('mexican-feather-mosaic-light','Forces & Energy',1),
	('lusterware-metallic-clay','Art & Expression',0),
	('lusterware-metallic-clay','Matter',1),
	('ebru-painting-on-water','Art & Expression',0),
	('ebru-painting-on-water','Planet Earth',1),
	('ebru-painting-on-water','Matter',2),
	('fore-edge-disappearing-painting','Art & Expression',0),
	('rainbow-eucalyptus-bark-clock','Living World',0),
	('rainbow-eucalyptus-bark-clock','Planet Earth',1),
	('rainbow-eucalyptus-bark-clock','Art & Expression',2),
	('nacreous-clouds-after-sunset','Matter',0),
	('nacreous-clouds-after-sunset','Planet Earth',1),
	('nacreous-clouds-after-sunset','Forces & Energy',2),
	('nebra-sky-disc-portable-cosmos','Time & History',0),
	('nebra-sky-disc-portable-cosmos','Matter',1),
	('nebra-sky-disc-portable-cosmos','Numbers & Logic',2),
	('dorodango-mud-mirror','Society',0),
	('qanat-desert-dotted-line','Design & Technology',0),
	('qanat-desert-dotted-line','Planet Earth',1),
	('reiner-gamma-magnetic-sunscreen','Cosmos',0),
	('reiner-gamma-magnetic-sunscreen','Forces & Energy',1),
	('odeillo-sunlight-furnace','Design & Technology',0),
	('odeillo-sunlight-furnace','Cosmos',1),
	('odeillo-sunlight-furnace','Matter',2),
	('isfahan-muqarnas-light-honeycomb','Art & Expression',0),
	('isfahan-muqarnas-light-honeycomb','Forces & Energy',1),
	('leafy-seadragon-false-leaves','Living World',0),
	('leafy-seadragon-false-leaves','Planet Earth',1),
	('bubble-chamber-invisible-tracks','Forces & Energy',0),
	('han-jade-burial-suit','Time & History',0),
	('han-jade-burial-suit','Belief & Ideas',1),
	('han-jade-burial-suit','Matter',2),
	('sand-mandala-impermanence','Society',0),
	('sand-mandala-impermanence','Belief & Ideas',1),
	('sand-mandala-impermanence','Matter',2),
	('ladakh-ice-stupa-spring-water','Food & Agriculture',0),
	('ladakh-ice-stupa-spring-water','Planet Earth',1),
	('ladakh-ice-stupa-spring-water','Matter',2),
	('enceladus-ocean-geysers','Cosmos',0),
	('enceladus-ocean-geysers','Planet Earth',1),
	('apollo-core-rope-software','Design & Technology',0),
	('apollo-core-rope-software','Language',1),
	('apollo-core-rope-software','Numbers & Logic',2),
	('apollo-core-rope-software','Society',3),
	('terracotta-soft-veil','Art & Expression',0),
	('terracotta-soft-veil','Matter',1),
	('corpse-flower-heat-and-scent','Living World',0),
	('corpse-flower-heat-and-scent','Body',1),
	('corpse-flower-heat-and-scent','Forces & Energy',2),
	('hair-ice-fungal-sculptor','Living World',0),
	('hair-ice-fungal-sculptor','Planet Earth',1),
	('hair-ice-fungal-sculptor','Matter',2),
	('oseberg-clinker-hull','Time & History',0),
	('oseberg-clinker-hull','Forces & Energy',1),
	('wayang-sculpture-and-shadow','Society',0),
	('wayang-sculpture-and-shadow','Art & Expression',1),
	('chand-baori-changing-waterline','Design & Technology',0),
	('chand-baori-changing-waterline','Planet Earth',1),
	('chand-baori-changing-waterline','Matter',2),
	('v838-mon-light-echo','Cosmos',0),
	('v838-mon-light-echo','Forces & Energy',1),
	('acoustic-levitation-standing-wave','Design & Technology',0),
	('acoustic-levitation-standing-wave','Planet Earth',1),
	('acoustic-levitation-standing-wave','Forces & Energy',2),
	('nested-puzzle-ball','Art & Expression',0),
	('blue-footed-booby-courtship-steps','Living World',0),
	('blue-footed-booby-courtship-steps','Mind',1),
	('blue-footed-booby-courtship-steps','Planet Earth',2),
	('penitentes-sun-carved-ice','Forces & Energy',0),
	('penitentes-sun-carved-ice','Planet Earth',1),
	('penitentes-sun-carved-ice','Matter',2),
	('shigir-idol-peat-time-capsule','Time & History',0),
	('shigir-idol-peat-time-capsule','Matter',1),
	('guna-mola-reverse-applique','Society',0),
	('guna-mola-reverse-applique','Art & Expression',1),
	('yakhchal-desert-ice-house','Design & Technology',0),
	('yakhchal-desert-ice-house','Planet Earth',1),
	('yakhchal-desert-ice-house','Matter',2),
	('mira-thirteen-light-year-tail','Cosmos',0),
	('mira-thirteen-light-year-tail','Forces & Energy',1),
	('transparent-wood-light-window','Design & Technology',0),
	('transparent-wood-light-window','Matter',1),
	('transparent-wood-light-window','Forces & Energy',2),
	('micromosaic-glass-painting','Art & Expression',0),
	('micromosaic-glass-painting','Matter',1),
	('giant-clam-solar-farm','Living World',0),
	('giant-clam-solar-farm','Body',1),
	('giant-clam-solar-farm','Cosmos',2),
	('ijen-burning-blue-sulfur','Matter',0),
	('ijen-burning-blue-sulfur','Planet Earth',1),
	('herculaneum-scroll-virtual-unwrapping','Time & History',0),
	('imigongo-earth-relief-patterns','Society',0),
	('imigongo-earth-relief-patterns','Planet Earth',1),
	('imigongo-earth-relief-patterns','Numbers & Logic',2),
	('imigongo-earth-relief-patterns','Art & Expression',3),
	('whale-fall-deep-sea-succession','Living World',0),
	('whale-fall-deep-sea-succession','Planet Earth',1),
	('hoags-object-ring-within-ring','Cosmos',0),
	('hoags-object-ring-within-ring','Numbers & Logic',1),
	('nanobionic-glowing-plants','Design & Technology',0),
	('nanobionic-glowing-plants','Living World',1),
	('carved-lacquer-hidden-layers','Art & Expression',0),
	('satin-bowerbird-blue-gallery','Living World',0),
	('satin-bowerbird-blue-gallery','Mind',1),
	('lichtenberg-frozen-lightning','Forces & Energy',0),
	('lichtenberg-frozen-lightning','Matter',1),
	('great-zimbabwe-dry-stone-curves','Time & History',0),
	('great-zimbabwe-dry-stone-curves','Matter',1),
	('great-zimbabwe-dry-stone-curves','Design & Technology',2),
	('maori-feather-cloak-weaving','Society',0),
	('maori-feather-cloak-weaving','Art & Expression',1),
	('salmon-carry-ocean-into-forest','Living World',0),
	('salmon-carry-ocean-into-forest','Planet Earth',1),
	('phobos-stickney-near-shatter','Cosmos',0),
	('frequency-comb-ruler-for-light','Design & Technology',0),
	('frequency-comb-ruler-for-light','Cosmos',1),
	('frequency-comb-ruler-for-light','Forces & Energy',2),
	('bojagi-scraps-into-light','Art & Expression',0),
	('bojagi-scraps-into-light','Planet Earth',1),
	('bojagi-scraps-into-light','Forces & Energy',2),
	('frogfish-fin-fishing-rod','Living World',0),
	('frogfish-fin-fishing-rod','Body',1),
	('green-flash-last-sunlight','Forces & Energy',0),
	('green-flash-last-sunlight','Planet Earth',1),
	('cyrus-cylinder-buried-proclamation','Time & History',0),
	('cyrus-cylinder-buried-proclamation','Language',1),
	('cyrus-cylinder-buried-proclamation','Matter',2),
	('roman-hypocaust-heated-floor','Design & Technology',0),
	('roman-hypocaust-heated-floor','Forces & Energy',1),
	('roman-hypocaust-heated-floor','Time & History',2),
	('solar-corona-hotter-than-surface','Cosmos',0),
	('bacterial-concrete-heals-cracks','Design & Technology',0),
	('bacterial-concrete-heals-cracks','Living World',1),
	('bacterial-concrete-heals-cracks','Planet Earth',2),
	('bacterial-concrete-heals-cracks','Matter',3),
	('pygmy-seahorse-coral-camouflage','Living World',0),
	('pygmy-seahorse-coral-camouflage','Mind',1),
	('pygmy-seahorse-coral-camouflage','Planet Earth',2),
	('light-pillars-floating-mirrors','Forces & Energy',0),
	('sanxingdui-protruding-eyes','Time & History',0),
	('sanxingdui-protruding-eyes','Matter',1),
	('kintsugi-golden-repair','Society',0),
	('kintsugi-golden-repair','Matter',1),
	('living-root-bridge-stronger','Design & Technology',0),
	('living-root-bridge-stronger','Living World',1),
	('daphnis-ring-wavemaker','Cosmos',0),
	('daphnis-ring-wavemaker','Planet Earth',1),
	('daphnis-ring-wavemaker','Forces & Energy',2),
	('daphnis-ring-wavemaker','Numbers & Logic',3),
	('aerogel-solid-smoke','Design & Technology',0),
	('aerogel-solid-smoke','Cosmos',1),
	('aerogel-solid-smoke','Matter',2),
	('aerogel-solid-smoke','Forces & Energy',3),
	('holbein-anamorphic-skull','Art & Expression',0),
	('holbein-anamorphic-skull','Mind',1),
	('peacock-spider-rainbow-fan','Living World',0),
	('peacock-spider-rainbow-fan','Mind',1),
	('peacock-spider-rainbow-fan','Planet Earth',2),
	('peacock-spider-rainbow-fan','Art & Expression',3),
	('snow-rollers-wind-sculpture','Forces & Energy',0),
	('snow-rollers-wind-sculpture','Planet Earth',1),
	('snow-rollers-wind-sculpture','Matter',2),
	('lion-man-mammoth-ivory','Time & History',0),
	('lion-man-mammoth-ivory','Art & Expression',1),
	('zellige-infinite-geometry','Society',0),
	('zellige-infinite-geometry','Numbers & Logic',1),
	('fog-net-drinking-water','Design & Technology',0),
	('fog-net-drinking-water','Planet Earth',1),
	('fog-net-drinking-water','Matter',2),
	('ceres-occator-salt-deposits','Cosmos',0),
	('gecko-gripper-space','Design & Technology',0),
	('gecko-gripper-space','Living World',1),
	('gecko-gripper-space','Cosmos',2),
	('goryeo-celadon-hidden-inlay','Art & Expression',0),
	('goryeo-celadon-hidden-inlay','Matter',1),
	('resurrection-plant-rehydration','Living World',0),
	('resurrection-plant-rehydration','Body',1),
	('resurrection-plant-rehydration','Planet Earth',2),
	('romanesco-fibonacci-growth','Numbers & Logic',0),
	('romanesco-fibonacci-growth','Living World',1),
	('terracotta-warriors-lost-color','Time & History',0),
	('terracotta-warriors-lost-color','Matter',1),
	('terracotta-warriors-lost-color','Forces & Energy',2),
	('shipibo-kene-visual-language','Society',0),
	('shipibo-kene-visual-language','Language',1),
	('shipibo-kene-visual-language','Matter',2),
	('shipibo-kene-visual-language','Art & Expression',3),
	('qeswachaka-annual-rebuild','Society',0),
	('qeswachaka-annual-rebuild','Design & Technology',1),
	('eta-carinae-survived-eruption','Cosmos',0),
	('robobee-paperclip-flight','Design & Technology',0),
	('arcimboldo-vertumnus-harvest-face','Art & Expression',0),
	('giant-waterlily-floating-truss','Living World',0),
	('giant-waterlily-floating-truss','Body',1),
	('giant-waterlily-floating-truss','Planet Earth',2),
	('giant-waterlily-floating-truss','Matter',3),
	('fallstreak-hole-aircraft','Forces & Energy',0),
	('fallstreak-hole-aircraft','Planet Earth',1),
	('dogu-goggle-eyes','Time & History',0),
	('dogu-goggle-eyes','Matter',1),
	('dogu-goggle-eyes','Art & Expression',2),
	('gelede-masks-oral-history','Society',0),
	('gelede-masks-oral-history','Belief & Ideas',1),
	('aflaj-water-by-time','Society',0),
	('aflaj-water-by-time','Food & Agriculture',1),
	('aflaj-water-by-time','Planet Earth',2),
	('aflaj-water-by-time','Matter',3),
	('pan-flying-saucer-moon','Cosmos',0),
	('pufferfish-underwater-sand-garden','Living World',0),
	('pufferfish-underwater-sand-garden','Mind',1),
	('pufferfish-underwater-sand-garden','Numbers & Logic',2),
	('pufferfish-underwater-sand-garden','Planet Earth',3),
	('pollia-berry-color-without-pigment','Living World',0),
	('pollia-berry-color-without-pigment','Matter',1),
	('pollia-berry-color-without-pigment','Forces & Energy',2),
	('pistol-shrimp-flashing-cavitation','Living World',0),
	('pistol-shrimp-flashing-cavitation','Forces & Energy',1),
	('pistol-shrimp-flashing-cavitation','Matter',2),
	('siphonophore-colony-one-body','Living World',0),
	('siphonophore-colony-one-body','Planet Earth',1),
	('siphonophore-colony-one-body','Body',2),
	('wood-frog-freezes-and-restarts','Living World',0),
	('wood-frog-freezes-and-restarts','Body',1),
	('wood-frog-freezes-and-restarts','Matter',2),
	('red-sprites-above-thunderstorms','Forces & Energy',0),
	('red-sprites-above-thunderstorms','Planet Earth',1),
	('red-sprites-above-thunderstorms','Cosmos',2),
	('naica-giant-gypsum-crystals','Matter',0),
	('naica-giant-gypsum-crystals','Planet Earth',1),
	('naica-giant-gypsum-crystals','Time & History',2),
	('brocken-spectre-rainbow-shadow','Forces & Energy',0),
	('brocken-spectre-rainbow-shadow','Mind',1),
	('brocken-spectre-rainbow-shadow','Planet Earth',2),
	('rainbow-is-really-a-circle','Forces & Energy',0),
	('rainbow-is-really-a-circle','Numbers & Logic',1),
	('rainbow-is-really-a-circle','Planet Earth',2),
	('egyptian-blue-hippo-lotus-rebirth','Time & History',0),
	('egyptian-blue-hippo-lotus-rebirth','Belief & Ideas',1),
	('egyptian-blue-hippo-lotus-rebirth','Art & Expression',2),
	('liangzhu-jade-cong-enigma','Time & History',0),
	('liangzhu-jade-cong-enigma','Belief & Ideas',1),
	('liangzhu-jade-cong-enigma','Art & Expression',2),
	('liangzhu-jade-cong-enigma','Matter',3),
	('oxus-gold-chariot-protective-face','Time & History',0),
	('oxus-gold-chariot-protective-face','Belief & Ideas',1),
	('oxus-gold-chariot-protective-face','Art & Expression',2),
	('oxus-gold-chariot-protective-face','Design & Technology',3),
	('babylon-processional-brick-lions','Time & History',0),
	('babylon-processional-brick-lions','Belief & Ideas',1),
	('babylon-processional-brick-lions','Art & Expression',2),
	('babylon-processional-brick-lions','Society',3),
	('djenne-mosque-annual-replastering','Society',0),
	('djenne-mosque-annual-replastering','Belief & Ideas',1),
	('djenne-mosque-annual-replastering','Design & Technology',2),
	('djenne-mosque-annual-replastering','Art & Expression',3),
	('jeju-haenyeo-one-breath-harvest','Society',0),
	('jeju-haenyeo-one-breath-harvest','Planet Earth',1),
	('jeju-haenyeo-one-breath-harvest','Body',2),
	('jeju-haenyeo-one-breath-harvest','Food & Agriculture',3),
	('theyyam-costume-living-deity','Art & Expression',0),
	('theyyam-costume-living-deity','Belief & Ideas',1),
	('theyyam-costume-living-deity','Society',2),
	('ikat-pattern-dyed-before-weaving','Art & Expression',0),
	('ikat-pattern-dyed-before-weaving','Matter',1),
	('ikat-pattern-dyed-before-weaving','Society',2),
	('ikat-pattern-dyed-before-weaving','Design & Technology',3),
	('dutch-sand-motor-moving-coast','Design & Technology',0),
	('dutch-sand-motor-moving-coast','Planet Earth',1),
	('dutch-sand-motor-moving-coast','Forces & Energy',2),
	('oyster-reef-filter-and-breakwater','Living World',0),
	('oyster-reef-filter-and-breakwater','Planet Earth',1),
	('oyster-reef-filter-and-breakwater','Forces & Energy',2),
	('slime-mold-designs-rail-network','Living World',0),
	('slime-mold-designs-rail-network','Numbers & Logic',1),
	('slime-mold-designs-rail-network','Design & Technology',2),
	('red-rectangle-nebula-ladder','Cosmos',0),
	('red-rectangle-nebula-ladder','Forces & Energy',1),
	('red-rectangle-nebula-ladder','Matter',2),
	('miranda-patchwork-moon-cliffs','Cosmos',0),
	('miranda-patchwork-moon-cliffs','Matter',1),
	('miranda-patchwork-moon-cliffs','Forces & Energy',2),
	('cosmic-hand-pulsar-wind-nebula','Cosmos',0),
	('cosmic-hand-pulsar-wind-nebula','Forces & Energy',1),
	('comet-67p-rubber-duck-collision','Cosmos',0),
	('comet-67p-rubber-duck-collision','Matter',1),
	('comet-67p-rubber-duck-collision','Time & History',2),
	('origami-solar-array-bloom','Design & Technology',0),
	('origami-solar-array-bloom','Cosmos',1),
	('origami-solar-array-bloom','Numbers & Logic',2),
	('metal-foam-floats-on-water','Design & Technology',0),
	('metal-foam-floats-on-water','Matter',1),
	('metal-foam-floats-on-water','Forces & Energy',2),
	('sofi-soft-robotic-fish','Design & Technology',0),
	('sofi-soft-robotic-fish','Living World',1),
	('sofi-soft-robotic-fish','Mind',2),
	('millefiori-thousand-glass-flowers','Art & Expression',0),
	('millefiori-thousand-glass-flowers','Matter',1),
	('millefiori-thousand-glass-flowers','Design & Technology',2),
	('martinez-black-on-black-pottery','Art & Expression',0),
	('martinez-black-on-black-pottery','Matter',1),
	('martinez-black-on-black-pottery','Society',2),
	('reverse-glass-painting-backward','Art & Expression',0),
	('reverse-glass-painting-backward','Matter',1),
	('reverse-glass-painting-backward','Design & Technology',2)
)
INSERT OR IGNORE INTO `landing_recommendation_dimensions` (`recommendation_id`,`dimension`,`position`)
SELECT c.`recommendation_id`, c.`dimension`, c.`position`
FROM `curated` c
JOIN `landing_recommendations` r ON r.`id` = c.`recommendation_id`;
