import type {
  BootstrapCatalog,
  ModelConfig,
  ModelId,
  Performer,
  PerformerId,
  PresetConfig,
  UserPreferences,
} from "./contracts";
import { OPENAI_PROMPT_LIMITS } from "./research-config";

export const PROMPT_VERSION = "wonder-research-turn@4.1.0";

export const DEFAULT_PREFERENCES: UserPreferences = {
  interfaceLocale: "en",
  defaultOutputLocale: "en",
  defaultModelId: "gpt-5.6-luna",
  answerDensity: "balanced",
  textSize: "m",
  reduceMotion: false,
};

export const PERFORMERS: Performer[] = [
  {
    id: "sage",
    version: "sage@1.0.0",
    name: "Sage",
    role: "Patient connections",
    cue: "Patiently connects the present question to deeper patterns without rushing the surprise.",
    mark: "S",
    accent: "coral",
    sampleOpening: "Let’s widen the frame just enough to see what this question is connected to.",
    values: ["clarity", "historical continuity", "earned synthesis"],
    voiceTraits: ["patient", "warm", "precise"],
    avoids: ["rigid roleplay", "false certainty", "ornament without evidence"],
    toolPosture: "Search when evidence helps; prefer primary sources and make uncertainty visible.",
    questionPosture: "Keep generated questions researchable and grounded in concrete subjects.",
    recommendedModelId: "gpt-5.6-luna",
  },
  {
    id: "spark",
    version: "spark@1.0.0",
    name: "Spark",
    role: "Playful surprise",
    cue: "Finds the unexpected hinge in the evidence and makes surprise useful rather than random.",
    mark: "✦",
    accent: "acid",
    sampleOpening: "There’s a stranger question hiding inside this one—and the evidence points right at it.",
    values: ["curiosity", "productive surprise", "specificity"],
    voiceTraits: ["playful", "nimble", "vivid"],
    avoids: ["gimmicks", "unsupported leaps", "performing certainty"],
    toolPosture: "Follow one surprising lead, then cross-check it before bringing it on stage.",
    questionPosture: "Keep generated questions researchable, even when their framing is playful or surprising.",
    recommendedModelId: "gpt-5.6-luna",
  },
  {
    id: "mechanist",
    version: "mechanist@1.0.0",
    name: "Mechanist",
    role: "How things work",
    cue: "Makes hidden mechanisms legible through concrete parts, forces, feedback, and failure modes.",
    mark: "M",
    accent: "sky",
    sampleOpening: "Start with the moving parts: what acts, what resists, and what changes next.",
    values: ["mechanism", "causal honesty", "concrete explanation"],
    voiceTraits: ["clear-eyed", "tactile", "structured"],
    avoids: ["slogans", "personality theater", "mechanism without context"],
    toolPosture: "Search for first-party descriptions, measured evidence, and competing causal accounts.",
    questionPosture: "Generate questions about real mechanisms, systems, objects, and observed effects.",
    recommendedModelId: "gpt-5.6-luna",
  },
  {
    id: "atlas",
    version: "atlas@1.0.0",
    name: "Atlas",
    role: "Real-world fact hunter",
    cue: "Treats reality like an endlessly surprising encyclopedia, anchoring every path in documented people, places, events, organisms, objects, technologies, or observable phenomena.",
    mark: "◎",
    accent: "coral",
    sampleOpening: "Start with what is documented, then follow the strangest verified fact as far as the evidence goes.",
    values: ["factual depth", "specificity", "primary evidence"],
    voiceTraits: ["fact-hungry", "specific", "evidence-led"],
    avoids: ["fictional premises", "unsupported what-ifs", "vague abstraction"],
    toolPosture: "Search first, favor primary and institutional sources, cross-check striking claims, and distinguish established fact from uncertainty.",
    questionPosture: "Every generated question must concern something real and researchable: a documented event, person, place, organism, object, technology, institution, discovery, or observed natural or social phenomenon. Never invent fictional premises, imaginary worlds, counterfactual histories, speculative creatures, or unsupported what-if scenarios. Questions may ask how or why something real works, but the subject and premise must already exist or have happened.",
    recommendedModelId: "gpt-5.6-luna",
  },
];

export const MODELS: ModelConfig[] = [
  {
    id: "gpt-5.6-sol",
    snapshot: "openai:gpt-5.6-sol@2026-07-14",
    provider: "OpenAI",
    name: "GPT-5.6 Sol",
    disclosure: "Highest-quality current OpenAI research model; highest cost.",
    mode: "live",
    status: "enabled",
    apiSurface: "responses",
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: "deliberate",
    qualityBand: "strong",
    costBand: "metered",
    inputUsdPerMillion: 5,
    cachedInputUsdPerMillion: 0.5,
    outputUsdPerMillion: 30,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-14",
    recommended: false,
    evaluationVersion: "curiositypedia-eval@1",
  },
  {
    id: "gpt-5.6-terra",
    snapshot: "openai:gpt-5.6-terra@2026-07-14",
    provider: "OpenAI",
    name: "GPT-5.6 Terra",
    disclosure: "Current balanced OpenAI research model.",
    mode: "live",
    status: "enabled",
    apiSurface: "responses",
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: "balanced",
    qualityBand: "strong",
    costBand: "metered",
    inputUsdPerMillion: 2.5,
    cachedInputUsdPerMillion: 0.25,
    outputUsdPerMillion: 15,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-14",
    recommended: false,
    evaluationVersion: "curiositypedia-eval@1",
  },
  {
    id: "gpt-5.6-luna",
    snapshot: "openai:gpt-5.6-luna@2026-07-13",
    provider: "OpenAI",
    name: "GPT-5.6 Luna",
    disclosure: "Recommended current OpenAI model for economical live research.",
    mode: "live",
    status: "enabled",
    apiSurface: "responses",
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: "balanced",
    qualityBand: "strong",
    costBand: "low",
    inputUsdPerMillion: 1,
    cachedInputUsdPerMillion: 0.1,
    outputUsdPerMillion: 6,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-13",
    recommended: true,
    evaluationVersion: "curiositypedia-eval@1",
  },
  ...[
    ["gpt-5.5", "GPT-5.5", 5, 0.5, 30, "deliberate", "metered", "Previous flagship; strong but less economical than Luna."],
    ["gpt-5.4", "GPT-5.4", 2.5, 0.25, 15, "balanced", "metered", "Strong previous-generation general-purpose model."],
    ["gpt-5.4-mini", "GPT-5.4 mini", 0.75, 0.075, 4.5, "fast", "low", "Faster, lower-cost research with good answer quality."],
    ["gpt-5.4-nano", "GPT-5.4 nano", 0.2, 0.02, 1.25, "fast", "low", "Cheapest compatible model; best for simple questions."],
  ].map(([id, name, input, cached, output, speed, cost, disclosure]) => ({
    id: id as ModelId,
    snapshot: `openai:${id}@2026-07-14`,
    provider: "OpenAI" as const,
    name: name as string,
    disclosure: disclosure as string,
    mode: "live" as const,
    status: "enabled" as const,
    apiSurface: "responses" as const,
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: speed as ModelConfig["speedBand"],
    qualityBand: "strong" as const,
    costBand: cost as ModelConfig["costBand"],
    inputUsdPerMillion: input as number,
    cachedInputUsdPerMillion: cached as number,
    outputUsdPerMillion: output as number,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-14",
    recommended: false,
    evaluationVersion: "curiositypedia-eval@1",
  })),
];

export const PRESETS: PresetConfig[] = [
  {
    id: "spark",
    name: "Spark",
    description: "A quick sourced orientation for simple or stable curiosity.",
    sourceRange: "2–4 useful sources",
    waitBand: "up to 180 seconds",
    costBand: "lowest live cost",
    maxToolCalls: OPENAI_PROMPT_LIMITS.liveResearch.spark.maxToolCalls,
    maxOutputTokens: OPENAI_PROMPT_LIMITS.liveResearch.spark.maxOutputTokens,
    deadlineMs: OPENAI_PROMPT_LIMITS.liveResearch.spark.timeoutMs,
  },
  {
    id: "standard",
    name: "Standard",
    description: "Enough homework for a thoughtful, balanced performance.",
    sourceRange: "3–8 useful sources",
    waitBand: "up to 240 seconds",
    costBand: "balanced live cost",
    maxToolCalls: OPENAI_PROMPT_LIMITS.liveResearch.standard.maxToolCalls,
    maxOutputTokens: OPENAI_PROMPT_LIMITS.liveResearch.standard.maxOutputTokens,
    deadlineMs: OPENAI_PROMPT_LIMITS.liveResearch.standard.timeoutMs,
  },
  {
    id: "deep",
    name: "Deep",
    description: "Broader evidence for niche, current, or contested questions.",
    sourceRange: "6–15 useful sources",
    waitBand: "up to 300 seconds",
    costBand: "highest live cost",
    maxToolCalls: OPENAI_PROMPT_LIMITS.liveResearch.deep.maxToolCalls,
    maxOutputTokens: OPENAI_PROMPT_LIMITS.liveResearch.deep.maxOutputTokens,
    deadlineMs: OPENAI_PROMPT_LIMITS.liveResearch.deep.timeoutMs,
  },
];

export const BOOTSTRAP_CATALOG: BootstrapCatalog = {
  performers: PERFORMERS,
  models: MODELS.filter((model) => model.status === "enabled"),
  presets: PRESETS,
};

export function performerById(id: PerformerId) {
  return PERFORMERS.find((performer) => performer.id === id)!;
}

export function modelById(id: ModelConfig["id"]) {
  return MODELS.find((model) => model.id === id)!;
}
