import type {
  BootstrapCatalog,
  ModelConfig,
  ModelId,
  Performer,
  PerformerId,
  PresetConfig,
  UserPreferences,
} from "./contracts";

export const PROMPT_VERSION = "wonder-research-turn@3.2.0";
export const TURN_SCHEMA_VERSION = "wonder-turn-draft@4";

export const DEFAULT_PREFERENCES: UserPreferences = {
  answerDensity: "balanced",
  textSize: "m",
  imagePreference: "when-useful",
  speechRate: 1,
  reduceMotion: false,
};

export const PERFORMERS: Performer[] = [
  {
    id: "sage",
    version: "sage@1.0.0",
    name: "Sage",
    role: "Patient connections",
    cue: "Patiently connects the present question to deeper patterns without rushing the surprise.",
    mark: "S",
    accent: "coral",
    sampleOpening: "Let’s widen the frame just enough to see what this question is connected to.",
    values: ["clarity", "historical continuity", "earned synthesis"],
    voiceTraits: ["patient", "warm", "precise"],
    avoids: ["rigid roleplay", "false certainty", "ornament without evidence"],
    toolPosture: "Search when evidence helps; prefer primary sources and make uncertainty visible.",
    recommendedModelId: "gpt-5.6-luna",
  },
  {
    id: "spark",
    version: "spark@1.0.0",
    name: "Spark",
    role: "Playful surprise",
    cue: "Finds the unexpected hinge in the evidence and makes surprise useful rather than random.",
    mark: "✦",
    accent: "acid",
    sampleOpening: "There’s a stranger question hiding inside this one—and the evidence points right at it.",
    values: ["curiosity", "productive surprise", "specificity"],
    voiceTraits: ["playful", "nimble", "vivid"],
    avoids: ["gimmicks", "unsupported leaps", "performing certainty"],
    toolPosture: "Follow one surprising lead, then cross-check it before bringing it on stage.",
    recommendedModelId: "gpt-5.6-luna",
  },
  {
    id: "mechanist",
    version: "mechanist@1.0.0",
    name: "Mechanist",
    role: "How things work",
    cue: "Makes hidden mechanisms legible through concrete parts, forces, feedback, and failure modes.",
    mark: "M",
    accent: "sky",
    sampleOpening: "Start with the moving parts: what acts, what resists, and what changes next.",
    values: ["mechanism", "causal honesty", "concrete explanation"],
    voiceTraits: ["clear-eyed", "tactile", "structured"],
    avoids: ["slogans", "personality theater", "mechanism without context"],
    toolPosture: "Search for first-party descriptions, measured evidence, and competing causal accounts.",
    recommendedModelId: "gpt-5.6-luna",
  },
];

export const MODELS: ModelConfig[] = [
  {
    id: "gpt-5.6-sol",
    snapshot: "openai:gpt-5.6-sol@2026-07-14",
    provider: "OpenAI",
    name: "GPT-5.6 Sol",
    disclosure: "Highest-quality current OpenAI research model; highest cost.",
    mode: "live",
    status: "enabled",
    apiSurface: "responses",
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: "deliberate",
    qualityBand: "strong",
    costBand: "metered",
    inputUsdPerMillion: 5,
    cachedInputUsdPerMillion: 0.5,
    outputUsdPerMillion: 30,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-14",
    recommended: false,
    evaluationVersion: "wonderdrive-eval@1",
  },
  {
    id: "gpt-5.6-terra",
    snapshot: "openai:gpt-5.6-terra@2026-07-14",
    provider: "OpenAI",
    name: "GPT-5.6 Terra",
    disclosure: "Current balanced OpenAI research model.",
    mode: "live",
    status: "enabled",
    apiSurface: "responses",
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: "balanced",
    qualityBand: "strong",
    costBand: "metered",
    inputUsdPerMillion: 2.5,
    cachedInputUsdPerMillion: 0.25,
    outputUsdPerMillion: 15,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-14",
    recommended: false,
    evaluationVersion: "wonderdrive-eval@1",
  },
  {
    id: "gpt-5.6-luna",
    snapshot: "openai:gpt-5.6-luna@2026-07-13",
    provider: "OpenAI",
    name: "GPT-5.6 Luna",
    disclosure: "Recommended current OpenAI model for economical live research.",
    mode: "live",
    status: "enabled",
    apiSurface: "responses",
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: "balanced",
    qualityBand: "strong",
    costBand: "low",
    inputUsdPerMillion: 1,
    cachedInputUsdPerMillion: 0.1,
    outputUsdPerMillion: 6,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-13",
    recommended: true,
    evaluationVersion: "wonderdrive-eval@1",
  },
  ...[
    ["gpt-5.5", "GPT-5.5", 5, 0.5, 30, "deliberate", "metered", "Previous flagship; strong but less economical than Luna."],
    ["gpt-5.4", "GPT-5.4", 2.5, 0.25, 15, "balanced", "metered", "Strong previous-generation general-purpose model."],
    ["gpt-5.4-mini", "GPT-5.4 mini", 0.75, 0.075, 4.5, "fast", "low", "Faster, lower-cost research with good answer quality."],
    ["gpt-5.4-nano", "GPT-5.4 nano", 0.2, 0.02, 1.25, "fast", "low", "Cheapest compatible model; best for simple questions."],
  ].map(([id, name, input, cached, output, speed, cost, disclosure]) => ({
    id: id as ModelId,
    snapshot: `openai:${id}@2026-07-14`,
    provider: "OpenAI" as const,
    name: name as string,
    disclosure: disclosure as string,
    mode: "live" as const,
    status: "enabled" as const,
    apiSurface: "responses" as const,
    tools: ["web search", "image search", "structured output"],
    reasoningModes: ["low", "medium", "high"],
    speedBand: speed as ModelConfig["speedBand"],
    qualityBand: "strong" as const,
    costBand: cost as ModelConfig["costBand"],
    inputUsdPerMillion: input as number,
    cachedInputUsdPerMillion: cached as number,
    outputUsdPerMillion: output as number,
    searchUsdPerCall: 0.01,
    priceEffectiveAt: "2026-07-14",
    recommended: false,
    evaluationVersion: "wonderdrive-eval@1",
  })),
];

export const STARTERS: Record<PerformerId, string[]> = {
  sage: [
    "Where does a city keep its memories?",
    "What can a map hide by being accurate?",
    "Why do some ideas feel inevitable?",
    "Can silence be designed?",
  ],
  spark: [
    "What does a building sound like?",
    "What can an ocean hear that we cannot?",
    "Could a shadow be public infrastructure?",
    "When does a mistake become a tradition?",
  ],
  mechanist: [
    "How does a room decide where an echo goes?",
    "What keeps a standard alive after its inventors leave?",
    "How does a repeated route become infrastructure?",
    "What makes a city develop its own sound?",
  ],
};

export const DISCOVERY_STARTERS = [
  { question: "How does a memory become part of a place?", topic: "memory and place" },
  { question: "What makes a useful standard survive its makers?", topic: "living standards" },
  { question: "Where does a city hide the work that keeps it alive?", topic: "urban systems" },
  { question: "Why do some sounds make a room feel larger?", topic: "acoustic space" },
  { question: "What can an accurate map still leave out?", topic: "maps and power" },
  { question: "How does a repeated shortcut become infrastructure?", topic: "emergent infrastructure" },
  { question: "Can a public space teach people how to behave?", topic: "behavioral design" },
  { question: "What does an ecosystem remember after a disturbance?", topic: "ecological memory" },
  { question: "Why do tools change the questions we are able to ask?", topic: "tools and inquiry" },
  { question: "How does a rumor acquire the shape of evidence?", topic: "information systems" },
  { question: "What makes a machine feel predictable to a person?", topic: "human-machine trust" },
  { question: "When does convenience become dependency?", topic: "systems dependency" },
  { question: "How do archives decide what the future can remember?", topic: "archives" },
  { question: "What can a boundary reveal by failing?", topic: "boundaries" },
  { question: "Why do networks become fragile as they become efficient?", topic: "network resilience" },
  { question: "How does an image become evidence?", topic: "visual evidence" },
  { question: "What keeps a tradition recognizable while it changes?", topic: "cultural continuity" },
  { question: "How does a neighborhood develop its own rhythm?", topic: "urban rhythm" },
  { question: "What makes one explanation easier to believe than another?", topic: "explanation and belief" },
  { question: "Where does uncertainty belong in a good decision?", topic: "decision-making" },
  { question: "How can a system be fair without treating everyone the same?", topic: "fair systems" },
  { question: "What does a measurement change simply by being watched?", topic: "measurement" },
  { question: "Why do invisible systems become visible when they break?", topic: "failure modes" },
  { question: "How does curiosity change after the first answer?", topic: "curiosity" },
] as const;

export const PRESETS: PresetConfig[] = [
  {
    id: "spark",
    name: "Spark",
    description: "A quick sourced orientation for simple or stable curiosity.",
    sourceRange: "2–4 useful sources",
    waitBand: "about 25 seconds",
    costBand: "lowest live cost",
    maxToolCalls: 2,
    maxOutputTokens: 1400,
    deadlineMs: 25_000,
  },
  {
    id: "standard",
    name: "Standard",
    description: "Enough homework for a thoughtful, balanced performance.",
    sourceRange: "3–8 useful sources",
    waitBand: "about 60 seconds",
    costBand: "balanced live cost",
    maxToolCalls: 5,
    maxOutputTokens: 2400,
    deadlineMs: 60_000,
  },
  {
    id: "deep",
    name: "Deep",
    description: "Broader evidence for niche, current, or contested questions.",
    sourceRange: "6–15 useful sources",
    waitBand: "up to 120 seconds",
    costBand: "highest live cost",
    maxToolCalls: 10,
    maxOutputTokens: 4000,
    deadlineMs: 120_000,
  },
];

export const PRESET_LABELS = Object.fromEntries(
  PRESETS.map((preset) => [preset.id, preset]),
) as Record<(typeof PRESETS)[number]["id"], PresetConfig>;

export const BOOTSTRAP_CATALOG: BootstrapCatalog = {
  performers: PERFORMERS,
  models: MODELS.filter((model) => model.status === "enabled"),
  presets: PRESETS,
  starters: STARTERS,
  discoveryStarters: [...DISCOVERY_STARTERS],
  promptVersion: PROMPT_VERSION,
  schemaVersion: TURN_SCHEMA_VERSION,
};

export function performerById(id: PerformerId) {
  return PERFORMERS.find((performer) => performer.id === id)!;
}

export function modelById(id: ModelConfig["id"]) {
  return MODELS.find((model) => model.id === id)!;
}
