import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative } from "node:path";

const projectRoot = new URL("../", import.meta.url);
const outputUrl = new URL("../docs/code-index.md", import.meta.url);
const roots = ["app", "lib", "db", "worker", "build", "tests", "scripts"];
const rootFiles = [
  "drizzle.config.ts",
  "eslint.config.mjs",
  "next.config.ts",
  "postcss.config.mjs",
  "vite.config.ts",
];
const extensions = new Set([".ts", ".tsx", ".mjs", ".css"]);

async function sourceFiles(path) {
  const entries = await readdir(new URL(path, projectRoot), { withFileTypes: true });
  const files = await Promise.all(entries.map((entry) => {
    const child = join(path, entry.name);
    return entry.isDirectory() ? sourceFiles(`${child}/`) : extensions.has(extname(child)) ? [child] : [];
  }));
  return files.flat();
}

const files = [...(await Promise.all(roots.map((root) => sourceFiles(`${root}/`)))).flat(), ...rootFiles]
  .sort();
const fileSet = new Set(files);

function resolveLocal(from, specifier) {
  if (!specifier.startsWith(".")) return null;
  const base = join(dirname(from), specifier);
  const candidates = [
    base,
    ...[".ts", ".tsx", ".mjs", ".css"].map((extension) => `${base}${extension}`),
    ...[".ts", ".tsx", ".mjs"].map((extension) => join(base, `index${extension}`)),
  ];
  return candidates.find((candidate) => fileSet.has(candidate)) ?? null;
}

async function dependencies(file) {
  const source = await readFile(new URL(`../${file}`, import.meta.url), "utf8");
  const specifiers = [
    ...source.matchAll(/\bfrom\s+["']([^"']+)["']/g),
    ...source.matchAll(/\bimport\s*\(\s*["']([^"']+)["']/g),
    ...source.matchAll(/\bimport\s+["']([^"']+)["']/g),
  ].map((match) => match[1]);
  return [...new Set(specifiers.map((value) => resolveLocal(file, value)).filter(Boolean))].sort();
}

const rows = await Promise.all(files.map(async (file) => {
  const imports = await dependencies(file);
  const links = imports.length
    ? imports.map((dependency) => "[`" + dependency + "`](../" + dependency + ")").join("<br>")
    : "—";
  return "| [`" + file + "`](../" + file + ") | " + links + " |";
}));

const document = `# WonderDrive code index

> Generated by \`npm run architecture:update\`. Do not edit this file by hand.

Read [architecture.md](architecture.md) for system boundaries and change rules. This index is the current local module graph; external packages and generated SQL migration history are intentionally omitted.

| Module | Direct local dependencies |
| --- | --- |
${rows.join("\n")}
`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputUrl, "utf8").catch(() => "");
  if (current !== document) {
    console.error("Architecture index is stale. Run `npm run architecture:update` and commit docs/code-index.md.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputUrl, document);
  console.log(`Updated ${relative(process.cwd(), outputUrl.pathname)} (${files.length} modules).`);
}
